import matplotlib.pyplot as plt
import numpy as np

plt.subplots(2, 3)

traind, testd, trainl, testl = np.load(open("mnist.npz", "rb")).values()
# a)
plt.subplot(2, 3, 1)
plt.title("Average")
avgtraind = np.mean(traind, axis=0)
plt.imshow(avgtraind)
# b)
plt.subplot(2, 3, 2)
plt.title("Variance")
plt.imshow(np.var(traind, axis=0))
# c)
plt.subplot(2, 3, 3)
plt.title("Deviation")
plt.imshow(np.std(traind, axis=0))
# d)
plt.subplot(234)
plt.title("Histogramm 13,13")
plt.hist(traind[1:500, 13, 13])
plt.subplot(235)
plt.title("Histogramm 0,0")
plt.hist(traind[1:500, 0, 0])
# e)
perSampleMax = np.max(traind, axis=(1, 2))
perSampleMin = np.min(traind, axis=(1, 2))
averageMax = np.average(perSampleMax, axis=0)
averageMin = np.average(perSampleMin, axis=0)
print("average max: " + str(averageMax))
print("average min: " + str(averageMin))
# f)
plt.subplot(236)
plt.title("Per Pixel Max")
plt.imshow(np.max(traind, axis=0))

plt.show()

plt.subplots(1, 3)
plt.subplot(131)
broad = np.outer(
    np.ndarray.flatten(traind[500, :, :]), np.ndarray.flatten(traind[500, :, :])
)
plt.imshow(broad)
plt.show()
